### ISSUE TITLE
Pop-up should be formatted to look better

### ISSUE THREAD

**Issue by nileshtrivedi** [nileshtrivedi/better#1]

**Comment by oxalorg** [comment]
I'll take a stab at this!

**Comment by oxalorg** [comment]
This is what I came up with, sending a PR in a bit!

![image](https://user-images.githubusercontent.com/4194289/89310273-1a1e8b00-d692-11ea-950b-9b5b0c839ea7.png)

**Comment by nileshtrivedi** [comment]
Love it. But we might want to suggest multiple alternatives. Also, the recommendation should also explain WHY Mozilla is better than Chrome. So, the copy should be a paragraph, rather than sub-heading and a CTA.

**Comment by oxalorg** [comment]
I was thinking that the subheading can be used to explain why it is better (`betterDescription`).

And if we add `betterHow` tags in the schema, we can use those to succinctly describe why the alternative is better.

Maybe we can have one "recommended alternative", and other non recommended alternatives which can be shown with a little less emphasis?

**Comment by nileshtrivedi** [comment]
Yes, that seems ideal. 👍 on description and tags.

**Comment by nileshtrivedi** [comment]
![image](https://user-images.githubusercontent.com/19304/89511472-97abdd80-d7ef-11ea-9af2-59f7e8cb4224.png)

This is how it looks now.
