### ISSUE TITLE
Don't inherit host site css for our popup UI

### ISSUE THREAD

**Issue by oxalorg** [nileshtrivedi/better#16]
The better popup is formatting differently on different sites as it's inherting css.

We should be able to stop this by setting some default styles on the root div of our popup.

**Comment by anirudhvarma12** [comment]
@oxalorg , what default styles are you planning to add? I can pick this one up.

**Comment by oxalorg** [comment]
@anirudhvarma12 I was thinking of not inhertting ANY properties at all.

Can you check this: https://developer.mozilla.org/en-US/docs/Web/CSS/all

We can probably do something like
```
betterDiv {
	all: unset;
}
```

That may remove the browser styling too? It's worth a shot.

If that doesn't work, we will have to manually override styles like link colors, margins, padding, font size, etc for all elements in our UI.

**Comment by anirudhvarma12** [comment]
@oxalorg , might make sense to inject a style tag for this? I was trying unset, but we would have to add the same for all elements. If we have style tags, we can do -

```css
.better-ext-container * {
  all: unset;
}
```

**Comment by oxalorg** [comment]
Yup that would work. 👍
