### ISSUE TITLE
Allow users to subscribe to multiple lists

### ISSUE THREAD

**Issue by nileshtrivedi** [nileshtrivedi/better#8]
This will be good for decentralization and separates content from the software.  Here is how uBlock does it: 
![image](https://user-images.githubusercontent.com/19304/89331231-046b8e80-d6af-11ea-9abf-e9b98c96968e.png)

Some code refactoring will be needed for this. Also, in the pop-up, we should then show the source of recommendation.

This is not urgent. We should first build one high-quality list as per #7. And then revisit this if users demand it (or managing our own list causes governance issues).

**Comment by oxalorg** [comment]
This will allow us to show different suggestions from different projects.

For example: 
- switching.software suggestions Fastmail as an alternative to Gmail
- privacytools.io suggestions Protonmail
- ...etc

**Comment by nileshtrivedi** [comment]
I think the popup UI does not need to change even with multiple lists. For every alternative shown in the popup, we can show a bottom text saying: "Recommended by switching.software, opensource.builders" etc. Or "Recommended by 3 out of your 5 sources."

**Comment by oxalorg** [comment]
> For every alternative shown in the popup

We can try and merge entries from different source lists with same names and/or same url, but there's a slight hiccup if neither are identical. 

If source1 lists an alternative to gmail as:
```
{
  url: "https://gmail.com",
  name: "Gmail",
  desc: "xyz"
}
```

and `source2` lists it as:

```
{
  url: "https://mail.google.com",
  name: "Google Mail",
  desc: "abc"
}
```

We won't be able to merge these two entries and they'll be shown separately.

I'm not sure how much of an issue will this be.
