### ISSUE TITLE
Schema of alternatives list

### ISSUE THREAD

**Issue by oxalorg** [nileshtrivedi/better#9]
For flexibility in terms of UI, Options, and other future features we should probably make the schema more normalised

```
[
	{
		"evilUrl": "https?:\/\/(www.)?google.com\/chrome",
		"betterUrl": "https://mozilla.com",
		"betterText": "Mozilla Firefox",
		"betterDescription": "Firefox is open source, backed by the Mozilla Foundation".
		"betterHow": [
			"ethical", "privacy-focused", "random-tag"
		],
	}
]
```

This should also help mitigate #3

**Comment by nileshtrivedi** [comment]
This assumes that we show a single alternative. Even if we end up implementing UI with a single CTA, I'd recommend keeping the  schema flexible with multiple alternatives. That way, the choice to show one one or more alternatives can be made by the extension (perhaps user-configurable), not recommendation providers.

**Comment by nileshtrivedi** [comment]
Another enhancement idea: The recommendation URL should be able to take params from the current URL. For eg: if you are visiting a particular book on Amazon.com whose ISBN can be picked from the URL, the same ISBN can be passed on to the alternatives like OpenLibrary. This can be done by using named captures in the regexp which seems to be supported in Javascript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges

**Comment by nileshtrivedi** [comment]
:100: for making it an object instead of array with implicit ordering. But big key names could be a problem when the list gets bigger. The objects will not just be kept in memory, but might also get cached in localStorage (which has 5MB limit). We might want to keep it a bit more light-weight.

**Comment by oxalorg** [comment]
> This assumes that we show a single alternative

I thought we could just keep it as a list and `evilUrl` does not need to be unique. Then we test the url for every entry?

```
[
	{
		"evilUrl": "https?:\/\/(www.)?google.com\/chrome",
		"betterUrl": "https://mozilla.com",
		"betterText": "Mozilla Firefox",
		"betterDescription": "Firefox is open source, backed by the Mozilla Foundation".
		"betterHow": [
			"ethical", "privacy-focused", "random-tag"
		],
	},
	{
		"evilUrl": "https?:\/\/(www.)?google.com\/chrome",
		"betterUrl": "https://brave.org",
		"betterText": "Brave Browser",
		"betterDescription": "Brave is open source, new-generation browser.".
		"betterHow": [
			"ethical", "privacy-focused", "chromium-based"
		],
	},
]
```

I'm not sure if there will be any significant performance impact. Any thoughts on this vs something like this:

```
[
	{
		"evilUrl": "https?:\/\/(www.)?google.com\/chrome",
		"alternatives": [
			{
				"betterUrl": "https://mozilla.com",
				"recommendedAlt": true,
				"betterText": "Mozilla Firefox",
				"betterDescription": "Firefox is open source, backed by the Mozilla Foundation".
				"betterHow": [
					"ethical", "privacy-focused", "random-tag"
				]
			},
			{
				"betterUrl": "https://brave.org",
				"recommendedAlt": false,
				"betterText": "Brave Browser",
				"betterDescription": "Brave is open source, new-generation browser.".
				"betterHow": [
					"ethical", "privacy-focused", "chromium-based"
				]
			},
		]
	}
]
```

> We might want to keep it a bit more light-weight.

I agree. We can start with smaller keys?

But can this problem be postponed to the future? I mean this would be a good problem to have, but we can always change the internal storage representation later on if we ever come close to hitting the 5mb limit, right?

**Comment by nileshtrivedi** [comment]
Agree. I like the alternatives approach because we only have to find the first matching entry. `recommendedAltIndex` can be removed if we always pick the first alternative as the primary. Tags can be omitted because description suffices for now.

**Comment by nileshtrivedi** [comment]
So:
```
[
	{
		"urlPattern": "https?:\/\/(www.)?google.com\/chrome",
				"alternatives": [
			{
				"url": "https://mozilla.com",
				"name": "Mozilla Firefox",
				"desc": "Firefox is open source, backed by the Mozilla Foundation".
			},
			{
				"url": "https://brave.org",
				"name": "Brave Browser",
				"desc": "Brave is open source, new-generation browser.".
							},
		]
	}
]
```

**Comment by oxalorg** [comment]
Perfect, this looks like we can roll with it for the time being!
